name: UnstableCoin Keeper

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  destabilize:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run keeper script
        env:
          PRIVATE_KEY: ${{ secrets.KEEPER_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
        run: npm run keeper
        
      - name: Log result
        run: echo "Destabilization attempt completed at $(date)"
